### PR TITLE
CUBMA update

### PR DESCRIPTION
**Pull request by tkcy**
Replaced CUBMA files with raw model files without the post-processing that was applied to previously submitted CUBMA files.

### CODE REVIEW

**Comment by nickreich** [comment]
Teresa- There are some "conflicts" with this PR and the master branch. I will try to take a look at it later, but if you have the chance to maybe make sure that you have updated your repository to the most recent version of all files before adding your new files there is a chance that would resolve this as well...

**Comment by tkcy** [comment]
Hi Nick,

From what I can figure out, it doesn’t like that I removed the 2018-19 real time forecasts.  I had deleted them, then copied the new 2018-19 files into the training folder.  So the file names moved from realtime to training folder, and the contents of the files were changed as well.

I could put the original 18-19 files back into the folder and try again if that’s the best way to resolve?

I tried to sync from the master branch just now but that is also giving me the same error messages since my folder now has my new files.  Now I know to sync before pull request in the future.


Teresa



On Oct 15, 2019, at 1:58 PM, Nicholas G Reich <notifications@github.com<mailto:notifications@github.com>> wrote:


Teresa- There are some "conflicts" with this PR and the master branch. I will try to take a look at it later, but if you have the chance to maybe make sure that you have updated your repository to the most recent version of all files before adding your new files there is a chance that would resolve this as well...

**Comment by tkcy** [comment]
More specifically, it looks like the problem is that since my last sync with the master directory, someone on your end moved the CUBMA 2018-19 files to the training folder while I also put different files for CUBMA 2018-19 into the same folder.  These 29 files are the source of the conflict, and my version should be used.

Thanks! Sorry I don’t know how to fix this myself.



On Oct 15, 2019, at 3:11 PM, Yamana, Teresa K. <tky2104@cumc.columbia.edu<mailto:tky2104@cumc.columbia.edu>> wrote:

Hi Nick,

From what I can figure out, it doesn’t like that I removed the 2018-19 real time forecasts.  I had deleted them, then copied the new 2018-19 files into the training folder.  So the file names moved from realtime to training folder, and the contents of the files were changed as well.

I could put the original 18-19 files back into the folder and try again if that’s the best way to resolve?

I tried to sync from the master branch just now but that is also giving me the same error messages since my folder now has my new files.  Now I know to sync before pull request in the future.


Teresa



On Oct 15, 2019, at 1:58 PM, Nicholas G Reich <notifications@github.com<mailto:notifications@github.com>> wrote:


Teresa- There are some "conflicts" with this PR and the master branch. I will try to take a look at it later, but if you have the chance to maybe make sure that you have updated your repository to the most recent version of all files before adding your new files there is a chance that would resolve this as well...

**Comment by nickreich** [comment]
I think I added the updated CU BMA files manually by downloading the files from your forked repo separately and then adding them manually. Can you double-check that I've corrected the right files in the right way?

**Comment by nickreich** [comment]
I think this is closed by earlier commit. Am closing this now, but am hoping that @tkcy will confirm at some point that the files look right...

**Comment by tkcy** [comment]
FIles look good. thank you!

On Oct 16, 2019, at 9:03 PM, Nicholas G Reich <notifications@github.com<mailto:notifications@github.com>> wrote:


I think this is closed by earlier commit. Am closing this now, but am hoping that @tkcy<https://urldefense.proofpoint.com/v2/url?u=https-3A__github.com_tkcy&d=DwMCaQ&c=G2MiLlal7SXE3PeSnG8W6_JBU6FcdVjSsBSbw6gcR0U&r=laz-qrRhDunc-NsMF8Ul08nHvPVHcFoyEpYiL7fejU0&m=mbfs2ouDc125WtWr41Bzt7WYA-kfjeKvndGTndeebnU&s=9gHNSl44LwOTrZ1_TjfloI1NCQyZMeovCRnI1KfBBVM&e=> will confirm at some point that the files look right...

**Pull request closed without merging**
